import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/search.module.css';
import { useGetGitHubTopicByName } from './queries/topic';

const ExploreTopic: NextPage = () => {
  const { data, error, loading } = useGetGitHubTopicByName({ name: 'react' });

  const topic = data?.topic;
  const relatedtopics = topic?.relatedTopics;
  console.log('relatedTopics: ', topic?.relatedTopics);
  console.log('data: ', data);
  // TODO: handle errors and loading

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.pageContainer}>
        <h1 className={styles.pageHeader}>GitHub Topic Explorer</h1>
        {topic?.name ? (
          <h2 className={styles.mainTopicHeader}>{topic?.name}</h2>
        ) : null}
        {/* TODO: Add search input */}
        <h3 className={styles.mainTopicHeader}>Related topics:</h3>
        {relatedtopics && relatedtopics.length > 0 ? (
          <ul className={styles.list}>
            {relatedtopics?.map((topic) => (
              <li key={topic?.id} className={styles.listItem}>
                {topic?.name ? (
                  <div className={styles.topicName}>{topic?.name}</div>
                ) : null}
                {topic?.stargazers?.totalCount ? (
                  <div>stars: {topic?.stargazers?.totalCount}</div>
                ) : null}
              </li>
            ))}
          </ul>
        ) : null}
      </div>
    </div>
  );
};

export default ExploreTopic;
